#!/bin/bash
ls -a | awk '

  BEGIN {

      files = ""

        }

  /^\./ {

      files = files ", " $0

          next

	    }

      /\/$/ {

          files = ", " $0 files

	      next

	        }

	  {

		      files = files ", " $0

		        }

		  END {

		      sub(/^, /, "", files)

		          print files "\n"

			    }

		    '


